services:
  node:
    image: node:23
    profiles:
      - dev
    working_dir: /app
    volumes:
      - .:/app

  markdownlint:
    image: peterdavehello/markdownlint
    volumes:
      - .:/md

  php:
    image: itkdev/php8.3-fpm:latest
    user: ${COMPOSE_USER:-deploy}
    volumes:
      - .:/app

  # https://github.com/tmknom/dockerfiles/tree/main/prettier
  prettier:
    image: tmknom/prettier
    volumes:
      - .:/work
