on: pull_request

name: PR Review

env:
  COMPOSE_USER: root

jobs:
  changelog:
    runs-on: ubuntu-latest
    name: Changelog should be updated
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Git fetch
        run: git fetch

      - name: Check that changelog has been updated.
        run: git diff --exit-code origin/${{ github.base_ref }} -- CHANGELOG.md && exit 1 || exit 0

  lint-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - run: |
          task lint:assets

  lint-composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - run: |
          task lint:composer

  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - run: |
          task lint:markdown

  lint-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - run: |
          task lint:php

  lint-twig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - run: |
          task lint:twig

  code-analysis-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: arduino/setup-task@v2
      - run: |
          task code-analysis:php

  assets-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
      - run: |
          task assets:build
      - run: |
          git diff --exit-code
